### ISSUE TITLE
Minimize, Maximize, and Close button big and blurry

### ISSUE THREAD

**Issue by ZechariahB** [flathub/org.gtk.Gtk3theme.Breeze#102]
On Flathub as of this written was introduced a change that made the window buttons bigger and blurrier than they should be which is very apparent on any window using a header bar.

Commit: 5c590deb90e7ce7bdf4f3ccd4d69e303acb8794bdcf3c8786068bf892fb840e5
Parent: db4c7e416f560d7f1fa1de6252bbeed6821f53a0b46e1987d5508bc6a96cbe2f
Subject: Update breeze-gtk-5.27.3.tar.xz to 5.27.4 (a13f5339)
Date: 2023-04-05 13:46:51 +0000

Previous commit db4c7e416f560d7f1fa1de6252bbeed6821f53a0b46e1987d5508bc6a96cbe2f did not have this issue.

**Comment by travier** [comment]
Please file a bug upstream in the KDE bug tracker

**Comment by ZechariahB** [comment]
Will do
