### ISSUE TITLE
"Info: runtime org.gtk.Gtk3theme.Breeze-Dark branch 3.22 is end-of-life, with reason"

### ISSUE THREAD

**Issue by kanansnote** [flathub/org.gtk.Gtk3theme.Breeze#121]
Hi there. I get this message when I do updates via terminal:

`Info: runtime org.gtk.Gtk3theme.Breeze-Dark branch 3.22 is end-of-life, with reason:
   This theme has been replaced by org.gtk.Gtk3theme.Breeze, see README for workaround on using system color schemes. https://github.com/flathub/org.gtk.Gtk3theme.Breeze#workarounds
Info: applications using this extension:
   org.mozilla.firefox, org.telegram.desktop, com.github.tchx84.Flatseal`

Hopefully, you are going to address this issue. Thanks.

**Comment by Justinzobel** [comment]
This is an issue with the applications you listed, not with the Breeze theme. You'll need to report it to them as they're the ones specifying the old version.
