### ISSUE TITLE
The "Restore" Button is Miscolored in Dark Mode

### ISSUE THREAD

**Issue by Kir-Antipov** [flathub/org.gtk.Gtk3theme.Breeze#199]
Hi! I've encountered a pretty strange problem: the "restore" button uses its light mode texture instead of the dark mode one. I tried reinstalling `org.gtk.Gtk3theme.Breeze` 6.1.4 with `--delete-data`, however, this didn't help.

![Example](https://github.com/user-attachments/assets/08e2bc66-0bd1-4883-9e6b-b33596c63ab6)

**Comment by xalt7x** [comment]
I guess, it's a duplicate of #94

**Comment by Kir-Antipov** [comment]
Yup, it absolutely is. Thanks for pointing me in the right direction, as I've been struggling with this problem for quite some time now :D
