### ISSUE TITLE
Dark theme workaround does not work

### ISSUE THREAD

**Issue by DomiStyle** [flathub/org.gtk.Gtk3theme.Breeze#97]
With `org.gtk.Gtk3theme.Breeze-Dark` being EOL I looked into the alternative but it does not work for me.
I added the following override: `flatpak override --user --filesystem=xdg-config/gtk-3.0:ro`.

Which works for some apps but Electron apps (like Bitwarden or Postman) will still show a white title bar:

![Screenshot_20230405_091842](https://user-images.githubusercontent.com/975131/230009625-2215e75c-3593-4caa-9ecb-f1db96bf9ad6.png)

![Screenshot_20230405_092406](https://user-images.githubusercontent.com/975131/230010435-2a9e1af3-1c55-46c2-9cf5-ad8837305921.png)

Cemu is also styled incorrectly:

![Screenshot_20230405_092138](https://user-images.githubusercontent.com/975131/230009847-62a72420-c710-4885-a384-c26589d3eddd.png)

I can get around the white title bar by setting `sudo flatpak override --system --env=GTK_THEME=Breeze`. Which will fix the title bars but not Cemu.

I cannot get around the Cemu issue without installing `org.gtk.Gtk3theme.Breeze-Dark` and setting `GTK_THEME` to `Breeze-Dark`.

Any ideas what the correct solution is?

**Comment by DomiStyle** [comment]
The context menu in Visual Studio Code does also not work without `org.gtk.Gtk3theme.Breeze-Dark` installed:

![Screenshot_20230405_101646](https://user-images.githubusercontent.com/975131/230023121-241c6391-4d1a-45c9-a8ea-62a50e30e5cd.png)

**Comment by vulongm** [comment]
For the flatpak theme apps usually select the dark mode by reading a [color scheme preference setting](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Settings). Might be an Electron related bug https://github.com/electron/electron/issues/33635

**Comment by DomiStyle** [comment]
> Might be an Electron related bug https://github.com/electron/electron/issues/33635

Not impossible but since it works when starting the AppImage natively for any Electron application I tried so far Flatpak has to do something differently. Cemu has this issue as well in the Flatpak but it's a plain GTK application.

Is there a way to force Breeze to always use the dark theme?

**Comment by DomiStyle** [comment]
Is there a workaround for this by now?
As soon as I remove `org.gtk.Gtk3theme.Breeze-Dark` many applications still stop using dark mode.

Some examples that still don't work:
* PrusaSlicer
* Bitwarden (white title bar)
* Visual Studio Code (context menu)
* Cemu
* Thunderbird (will use Gnome theme for title bar instead of KDE)
* MQTTX

**Comment by vulongm** [comment]
@DomiStyle For me VS Code, Cemu, and Thunderbird does work for Breeze Dark without any overrides set. Bitwarden does have the dark title bar but not the breeze dark menus. Are you noticing any differences with the overrides removed and if you change the GTK theme under applicaiton styles -> GNOME/GTK Application Style to default and back to Breeze?
![image](https://github.com/flathub/org.gtk.Gtk3theme.Breeze/assets/50088314/d46b820b-047b-4882-bf10-a3461b970f0c)

**Comment by DomiStyle** [comment]
That seems to have fixed the GNOME theme in Thunderbird and the context menu in Visual Studio code. Bitwarden still has the white bar as you mentioned and Cemu is also still in light mode.

PrusaSlicer and MQTTX are also still in light mode, with MQTTX set to sync with OS:
![image](https://github.com/flathub/org.gtk.Gtk3theme.Breeze/assets/975131/2a938c4d-ebb9-4762-8dd6-d49d26a9820b)

**Comment by DomiStyle** [comment]
Adding the override after setting the theme in KDE again, fixes the Bitwarden title bar, MQTTX, PrusaSlicer and Cemu. Can't really find any issues anymore now. Thanks!

So to recap:
* Remove the override
* Uninstall `org.gtk.Gtk3theme.Breeze-Dark`
* Set theme in KDE to Default
* Set theme in KDE to Breeze
* Add override again

**Comment by andrevmatos** [comment]
I'm still experiencing issues in NixOS unstable with latest KDE Plasma and flatpak.
`Breeze` is the only `Gtk3Theme` installed in flatpak. Breeze is also the only option in the GTK style chooser in System Settings. Here's my resulting `~/.config/gtk-3.0/settings.ini` (plus some auto-generated css files), exposed as `xdg-config/gtk-3.0:ro`:
```ini
[Settings]
gtk-application-prefer-dark-theme=true
gtk-button-images=true
gtk-cursor-theme-name=Oxygen_White
gtk-cursor-theme-size=24
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=Papirus-Dark
gtk-menu-images=true
gtk-modules=colorreload-gtk-module:window-decorations-gtk-module:appmenu-gtk-module
gtk-primary-button-warps-slider=false
gtk-shell-shows-menubar=1
gtk-theme-name=Breeze
gtk-toolbar-style=3
gtk-xft-dpi=142540
```

The gtk applications (e.g. Flatseal) insist in picking what seems like a default dark Gtk theme; when forcing with `--env=GTK_THEME=Breeze`, the apps use Breeze theme, but with a light colorscheme (even though the whole system is set to use dark themes).

**Comment by vulongm** [comment]
@andrevmatos I believe Flatseal in particular is a GTK4 libadwaita app and they usually don't pick up the other themes without forcing it. Is this also occurring in apps like Firefox?

**Comment by andrevmatos** [comment]
@vulongm On Firefox, most menus and dialogs use the chrome window style, but on some where this is noticeable (e.g. download file dialog), the style seems to match the default seen on the other Gtk apps, I think Adwaita? Definitely not Breeze buttons and comboboxes, nor color matching my scheme, which is Breeze Dark (seems to have a discrete blue tune, while Adwaita looks more brownish).

**Comment by DomiStyle** [comment]
It seems like with Plasma 6 (on Fedora 40) this issue has come back to haunt me.

Doesn't matter if with or without override, toggling back and forth between dark/light themes but the applications listed before (https://github.com/flathub/org.gtk.Gtk3theme.Breeze/issues/97#issuecomment-1707852849) all fail to apply the dark theme correctly.
Except Cemu, that one is working.

Interestingly, if I switch between light/dark theme while VS Code is running, it will apply the theme correctly. Once I restart the context menu is white again.

**Comment by GamerTechUni** [comment]
> It seems like with Plasma 6 (on Fedora 40) this issue has come back to haunt me.
> 
> Doesn't matter if with or without override, toggling back and forth between dark/light themes but the applications listed before ([#97 (comment)](https://github.com/flathub/org.gtk.Gtk3theme.Breeze/issues/97#issuecomment-1707852849)) all fail to apply the dark theme correctly. Except Cemu, that one is working.
> 
> Interestingly, if I switch between light/dark theme while VS Code is running, it will apply the theme correctly. Once I restart the context menu is white again.

I have a similar issue, where light themes work fine with the overrides, but with dark themes, x11 gtk apps (Electron) don't respect my theme. I believe it is caused by a misconfiguration with xsettingsd, where in the config file, the 'Net/ThemeName' property is set to "Breeze-Dark" when using a dark theme by gnome/gtk theme service in KDE Plasma 6. There is no Breeze-Dark gtk theme with flatpaks, so it falls back to the default theme. Wayland gtk apps do respect my theme.

A temporary workaround is to disable the gtk service in Settings > Session > Background Services and then uncheck 'GNOME/GTK Settings Synchronization Service'. Then change ~/.config/xsettingsd/xsettingsd.conf, so that the theme is 'Breeze'. This has the side effect of not synchronising the gtk theme with the kde theme. 

I'm on Fedora 40 with KDE Plasma 6.04

**Comment by DomiStyle** [comment]
@GamerTechUni That seems to do it for me as well, now I just need to get the cursors to not be all over the place and everything should be fine again.
